sudo: true
language: node_js
node_js: 'node'
cache:
  directories:
	- "node_modules"
addons:
  chrome: stable
before_install:
  - # TODO: why does this work?
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
